// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Data;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240126182815_mig")]
    partial class mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication3.Models.Gazete", b =>
                {
                    b.Property<int>("GazeteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GazeteId"), 1L, 1);

                    b.Property<string>("GazetFacebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GazeteAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GazeteAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GazeteEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GazeteInstagram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GazeteLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GazeteSlogan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GazeteTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GazeteYoutube")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GazeteId");

                    b.ToTable("Gazetes");
                });

            modelBuilder.Entity("WebApplication3.Models.Haberler", b =>
                {
                    b.Property<int>("HaberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HaberId"), 1L, 1);

                    b.Property<string>("HaberBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaberKonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HaberManset")
                        .HasColumnType("int");

                    b.Property<DateTime>("HaberTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Haberİcerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KatagoriId")
                        .HasColumnType("int");

                    b.Property<int>("KonumId")
                        .HasColumnType("int");

                    b.Property<int>("ResimId")
                        .HasColumnType("int");

                    b.Property<int>("YazarId")
                        .HasColumnType("int");

                    b.Property<int?>("YazarlarYazarId")
                        .HasColumnType("int");

                    b.HasKey("HaberId");

                    b.HasIndex("KatagoriId");

                    b.HasIndex("KonumId");

                    b.HasIndex("ResimId");

                    b.HasIndex("YazarlarYazarId");

                    b.ToTable("haberlers");
                });

            modelBuilder.Entity("WebApplication3.Models.Katagori", b =>
                {
                    b.Property<int>("KatagoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KatagoriId"), 1L, 1);

                    b.Property<string>("KatagoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KatagoriId");

                    b.ToTable("katagoris");
                });

            modelBuilder.Entity("WebApplication3.Models.Konumlar", b =>
                {
                    b.Property<int>("KonumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KonumId"), 1L, 1);

                    b.Property<string>("KonumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KonumId");

                    b.ToTable("Konumlars");
                });

            modelBuilder.Entity("WebApplication3.Models.Kulanıcılar", b =>
                {
                    b.Property<int>("KulanıcıId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KulanıcıId"), 1L, 1);

                    b.Property<string>("KulaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KulaniciSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YetkiId")
                        .HasColumnType("int");

                    b.HasKey("KulanıcıId");

                    b.HasIndex("YetkiId");

                    b.ToTable("Kulanıcılars");
                });

            modelBuilder.Entity("WebApplication3.Models.Reklam", b =>
                {
                    b.Property<int>("ReklamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReklamId"), 1L, 1);

                    b.Property<int>("KonumId")
                        .HasColumnType("int");

                    b.Property<int?>("KonumlarKonumId")
                        .HasColumnType("int");

                    b.Property<string>("ReklamKonusu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReklamResim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReklamId");

                    b.HasIndex("KonumlarKonumId");

                    b.ToTable("Reklamlars");
                });

            modelBuilder.Entity("WebApplication3.Models.Resimler", b =>
                {
                    b.Property<int>("ResimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResimId"), 1L, 1);

                    b.Property<string>("ResimAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResimId");

                    b.ToTable("Resimlers");
                });

            modelBuilder.Entity("WebApplication3.Models.Yazarlar", b =>
                {
                    b.Property<int>("YazarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazarId"), 1L, 1);

                    b.Property<string>("YazarAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazarEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazarResim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazarSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YazarId");

                    b.ToTable("Yazarlars");
                });

            modelBuilder.Entity("WebApplication3.Models.Yetkiler", b =>
                {
                    b.Property<int>("YetkiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YetkiId"), 1L, 1);

                    b.Property<string>("YetkiAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YetkiId");

                    b.ToTable("Yetkilers");
                });

            modelBuilder.Entity("WebApplication3.Models.Yorumlar", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YorumId"), 1L, 1);

                    b.Property<int>("HaberId")
                        .HasColumnType("int");

                    b.Property<int?>("HaberlersHaberId")
                        .HasColumnType("int");

                    b.Property<string>("YorumAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YorumMesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YorumId");

                    b.HasIndex("HaberlersHaberId");

                    b.ToTable("Yorumlars");
                });

            modelBuilder.Entity("WebApplication3.Models.Haberler", b =>
                {
                    b.HasOne("WebApplication3.Models.Katagori", "Katagori")
                        .WithMany("Haberlers")
                        .HasForeignKey("KatagoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Konumlar", "Konumlar")
                        .WithMany("Habers")
                        .HasForeignKey("KonumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Resimler", "Resimler")
                        .WithMany("Haberlers")
                        .HasForeignKey("ResimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Yazarlar", "Yazarlar")
                        .WithMany("Habers")
                        .HasForeignKey("YazarlarYazarId");

                    b.Navigation("Katagori");

                    b.Navigation("Konumlar");

                    b.Navigation("Resimler");

                    b.Navigation("Yazarlar");
                });

            modelBuilder.Entity("WebApplication3.Models.Kulanıcılar", b =>
                {
                    b.HasOne("WebApplication3.Models.Yetkiler", "Yetkiler")
                        .WithMany("Kulanıcılars")
                        .HasForeignKey("YetkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yetkiler");
                });

            modelBuilder.Entity("WebApplication3.Models.Reklam", b =>
                {
                    b.HasOne("WebApplication3.Models.Konumlar", "Konumlar")
                        .WithMany("Reklamlars")
                        .HasForeignKey("KonumlarKonumId");

                    b.Navigation("Konumlar");
                });

            modelBuilder.Entity("WebApplication3.Models.Yorumlar", b =>
                {
                    b.HasOne("WebApplication3.Models.Haberler", "Haberlers")
                        .WithMany("Yorumlars")
                        .HasForeignKey("HaberlersHaberId");

                    b.Navigation("Haberlers");
                });

            modelBuilder.Entity("WebApplication3.Models.Haberler", b =>
                {
                    b.Navigation("Yorumlars");
                });

            modelBuilder.Entity("WebApplication3.Models.Katagori", b =>
                {
                    b.Navigation("Haberlers");
                });

            modelBuilder.Entity("WebApplication3.Models.Konumlar", b =>
                {
                    b.Navigation("Habers");

                    b.Navigation("Reklamlars");
                });

            modelBuilder.Entity("WebApplication3.Models.Resimler", b =>
                {
                    b.Navigation("Haberlers");
                });

            modelBuilder.Entity("WebApplication3.Models.Yazarlar", b =>
                {
                    b.Navigation("Habers");
                });

            modelBuilder.Entity("WebApplication3.Models.Yetkiler", b =>
                {
                    b.Navigation("Kulanıcılars");
                });
#pragma warning restore 612, 618
        }
    }
}
